/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const accuracy: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "accuracy"
  ],
  mapper: {
    serializedName: "accuracy",
    defaultValue: 0,
    type: {
      name: "Number"
    }
  }
};
export const addressId: msRest.OperationURLParameter = {
  parameterPath: "addressId",
  mapper: {
    required: true,
    serializedName: "addressId",
    type: {
      name: "String"
    }
  }
};
export const baseSiteId: msRest.OperationURLParameter = {
  parameterPath: "baseSiteId",
  mapper: {
    required: true,
    serializedName: "baseSiteId",
    type: {
      name: "String"
    }
  }
};
export const baseStoreUid: msRest.OperationURLParameter = {
  parameterPath: "baseStoreUid",
  mapper: {
    required: true,
    serializedName: "baseStoreUid",
    type: {
      name: "String"
    }
  }
};
export const cartId: msRest.OperationURLParameter = {
  parameterPath: "cartId",
  mapper: {
    required: true,
    serializedName: "cartId",
    type: {
      name: "String"
    }
  }
};
export const catalog: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "catalog"
  ],
  mapper: {
    serializedName: "catalog",
    type: {
      name: "String"
    }
  }
};
export const catalogCode: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "catalogCode"
  ],
  mapper: {
    serializedName: "catalogCode",
    type: {
      name: "String"
    }
  }
};
export const catalogId: msRest.OperationURLParameter = {
  parameterPath: "catalogId",
  mapper: {
    required: true,
    serializedName: "catalogId",
    type: {
      name: "String"
    }
  }
};
export const catalogVersionId: msRest.OperationURLParameter = {
  parameterPath: "catalogVersionId",
  mapper: {
    required: true,
    serializedName: "catalogVersionId",
    type: {
      name: "String"
    }
  }
};
export const categoryCode: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "categoryCode"
  ],
  mapper: {
    serializedName: "categoryCode",
    type: {
      name: "String"
    }
  }
};
export const categoryId: msRest.OperationURLParameter = {
  parameterPath: "categoryId",
  mapper: {
    required: true,
    serializedName: "categoryId",
    type: {
      name: "String"
    }
  }
};
export const code0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "code"
  ],
  mapper: {
    serializedName: "code",
    type: {
      name: "String"
    }
  }
};
export const code1: msRest.OperationURLParameter = {
  parameterPath: "code",
  mapper: {
    required: true,
    serializedName: "code",
    type: {
      name: "String"
    }
  }
};
export const componentId: msRest.OperationURLParameter = {
  parameterPath: "componentId",
  mapper: {
    required: true,
    serializedName: "componentId",
    type: {
      name: "String"
    }
  }
};
export const consentCode: msRest.OperationURLParameter = {
  parameterPath: "consentCode",
  mapper: {
    required: true,
    serializedName: "consentCode",
    type: {
      name: "String"
    }
  }
};
export const consentTemplateId: msRest.OperationQueryParameter = {
  parameterPath: "consentTemplateId",
  mapper: {
    required: true,
    serializedName: "consentTemplateId",
    type: {
      name: "String"
    }
  }
};
export const consentTemplateVersion: msRest.OperationQueryParameter = {
  parameterPath: "consentTemplateVersion",
  mapper: {
    required: true,
    serializedName: "consentTemplateVersion",
    type: {
      name: "Number"
    }
  }
};
export const countyIsoCode: msRest.OperationURLParameter = {
  parameterPath: "countyIsoCode",
  mapper: {
    required: true,
    serializedName: "countyIsoCode",
    type: {
      name: "String"
    }
  }
};
export const currentPage: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "currentPage"
  ],
  mapper: {
    serializedName: "currentPage",
    defaultValue: 0,
    type: {
      name: "Number"
    }
  }
};
export const deliveryModeId: msRest.OperationQueryParameter = {
  parameterPath: "deliveryModeId",
  mapper: {
    required: true,
    serializedName: "deliveryModeId",
    type: {
      name: "String"
    }
  }
};
export const description: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "description"
  ],
  mapper: {
    serializedName: "description",
    type: {
      name: "String"
    }
  }
};
export const email: msRest.OperationQueryParameter = {
  parameterPath: "email",
  mapper: {
    required: true,
    serializedName: "email",
    type: {
      name: "String"
    }
  }
};
export const entryNumber: msRest.OperationURLParameter = {
  parameterPath: "entryNumber",
  mapper: {
    required: true,
    serializedName: "entryNumber",
    type: {
      name: "Number"
    }
  }
};
export const extendedMerchantCallback: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "extendedMerchantCallback"
  ],
  mapper: {
    serializedName: "extendedMerchantCallback",
    defaultValue: false,
    type: {
      name: "Boolean"
    }
  }
};
export const fields0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fields"
  ],
  mapper: {
    serializedName: "fields",
    defaultValue: 'DEFAULT',
    type: {
      name: "String"
    }
  }
};
export const fields1: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fields"
  ],
  mapper: {
    serializedName: "fields",
    defaultValue: 'BASIC',
    type: {
      name: "String"
    }
  }
};
export const fields2: msRest.OperationQueryParameter = {
  parameterPath: "fields",
  mapper: {
    required: true,
    serializedName: "fields",
    defaultValue: 'DEFAULT',
    type: {
      name: "String"
    }
  }
};
export const groupId: msRest.OperationURLParameter = {
  parameterPath: "groupId",
  mapper: {
    required: true,
    serializedName: "groupId",
    type: {
      name: "String"
    }
  }
};
export const latitude: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "latitude"
  ],
  mapper: {
    serializedName: "latitude",
    type: {
      name: "Number"
    }
  }
};
export const location: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "location"
  ],
  mapper: {
    serializedName: "location",
    type: {
      name: "String"
    }
  }
};
export const longitude: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "longitude"
  ],
  mapper: {
    serializedName: "longitude",
    type: {
      name: "Number"
    }
  }
};
export const max: msRest.OperationQueryParameter = {
  parameterPath: "max",
  mapper: {
    required: true,
    serializedName: "max",
    defaultValue: 10,
    type: {
      name: "Number"
    }
  }
};
export const maxCount: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "maxCount"
  ],
  mapper: {
    serializedName: "maxCount",
    type: {
      name: "Number"
    }
  }
};
export const name: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "name"
  ],
  mapper: {
    serializedName: "name",
    type: {
      name: "String"
    }
  }
};
export const newLogin: msRest.OperationQueryParameter = {
  parameterPath: "newLogin",
  mapper: {
    required: true,
    serializedName: "newLogin",
    type: {
      name: "String"
    }
  }
};
export const newParameter: msRest.OperationQueryParameter = {
  parameterPath: "newParameter",
  mapper: {
    required: true,
    serializedName: "new",
    type: {
      name: "String"
    }
  }
};
export const old: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "old"
  ],
  mapper: {
    serializedName: "old",
    type: {
      name: "String"
    }
  }
};
export const oldCartId: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "oldCartId"
  ],
  mapper: {
    serializedName: "oldCartId",
    type: {
      name: "String"
    }
  }
};
export const pageLabelOrId: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageLabelOrId"
  ],
  mapper: {
    serializedName: "pageLabelOrId",
    type: {
      name: "String"
    }
  }
};
export const pageSize0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageSize"
  ],
  mapper: {
    serializedName: "pageSize",
    defaultValue: 10,
    type: {
      name: "Number"
    }
  }
};
export const pageSize1: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageSize"
  ],
  mapper: {
    serializedName: "pageSize",
    defaultValue: 20,
    type: {
      name: "Number"
    }
  }
};
export const pageSize2: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageSize"
  ],
  mapper: {
    serializedName: "pageSize",
    defaultValue: 2147483647,
    type: {
      name: "Number"
    }
  }
};
export const pageType: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pageType"
  ],
  mapper: {
    serializedName: "pageType",
    defaultValue: 'ContentPage',
    type: {
      name: "String"
    }
  }
};
export const password: msRest.OperationQueryParameter = {
  parameterPath: "password",
  mapper: {
    required: true,
    serializedName: "password",
    type: {
      name: "String"
    }
  }
};
export const paymentDetailsId: msRest.OperationQueryParameter = {
  parameterPath: "paymentDetailsId",
  mapper: {
    required: true,
    serializedName: "paymentDetailsId",
    type: {
      name: "String"
    }
  }
};
export const productCode0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "productCode"
  ],
  mapper: {
    serializedName: "productCode",
    type: {
      name: "String"
    }
  }
};
export const productCode1: msRest.OperationURLParameter = {
  parameterPath: "productCode",
  mapper: {
    required: true,
    serializedName: "productCode",
    type: {
      name: "String"
    }
  }
};
export const promotionGroup: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "promotionGroup"
  ],
  mapper: {
    serializedName: "promotionGroup",
    type: {
      name: "String"
    }
  }
};
export const promotionId: msRest.OperationQueryParameter = {
  parameterPath: "promotionId",
  mapper: {
    required: true,
    serializedName: "promotionId",
    type: {
      name: "String"
    }
  }
};
export const query: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "query"
  ],
  mapper: {
    serializedName: "query",
    type: {
      name: "String"
    }
  }
};
export const radius: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "radius"
  ],
  mapper: {
    serializedName: "radius",
    defaultValue: 100000,
    type: {
      name: "Number"
    }
  }
};
export const referenceType: msRest.OperationQueryParameter = {
  parameterPath: "referenceType",
  mapper: {
    required: true,
    serializedName: "referenceType",
    type: {
      name: "String"
    }
  }
};
export const responseUrl: msRest.OperationQueryParameter = {
  parameterPath: "responseUrl",
  mapper: {
    required: true,
    serializedName: "responseUrl",
    type: {
      name: "String"
    }
  }
};
export const saveCartDescription: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "saveCartDescription"
  ],
  mapper: {
    serializedName: "saveCartDescription",
    type: {
      name: "String"
    }
  }
};
export const saveCartName: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "saveCartName"
  ],
  mapper: {
    serializedName: "saveCartName",
    type: {
      name: "String"
    }
  }
};
export const saved: msRest.OperationQueryParameter = {
  parameterPath: "saved",
  mapper: {
    required: true,
    serializedName: "saved",
    defaultValue: false,
    type: {
      name: "Boolean"
    }
  }
};
export const savedCartsOnly: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "savedCartsOnly"
  ],
  mapper: {
    serializedName: "savedCartsOnly",
    defaultValue: false,
    type: {
      name: "Boolean"
    }
  }
};
export const searchQueryContext: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "searchQueryContext"
  ],
  mapper: {
    serializedName: "searchQueryContext",
    type: {
      name: "String"
    }
  }
};
export const securityCode: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "securityCode"
  ],
  mapper: {
    serializedName: "securityCode",
    type: {
      name: "String"
    }
  }
};
export const sort0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sort"
  ],
  mapper: {
    serializedName: "sort",
    type: {
      name: "String"
    }
  }
};
export const sort1: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "sort"
  ],
  mapper: {
    serializedName: "sort",
    defaultValue: 'asc',
    type: {
      name: "String"
    }
  }
};
export const statuses: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "statuses"
  ],
  mapper: {
    serializedName: "statuses",
    type: {
      name: "String"
    }
  }
};
export const storeId: msRest.OperationURLParameter = {
  parameterPath: "storeId",
  mapper: {
    required: true,
    serializedName: "storeId",
    type: {
      name: "String"
    }
  }
};
export const storeName: msRest.OperationURLParameter = {
  parameterPath: "storeName",
  mapper: {
    required: true,
    serializedName: "storeName",
    type: {
      name: "String"
    }
  }
};
export const term: msRest.OperationQueryParameter = {
  parameterPath: "term",
  mapper: {
    required: true,
    serializedName: "term",
    type: {
      name: "String"
    }
  }
};
export const timestamp0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "timestamp"
  ],
  mapper: {
    serializedName: "timestamp",
    type: {
      name: "String"
    }
  }
};
export const timestamp1: msRest.OperationQueryParameter = {
  parameterPath: "timestamp",
  mapper: {
    required: true,
    serializedName: "timestamp",
    type: {
      name: "String"
    }
  }
};
export const toMergeCartGuid: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "toMergeCartGuid"
  ],
  mapper: {
    serializedName: "toMergeCartGuid",
    type: {
      name: "String"
    }
  }
};
export const type0: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "type"
  ],
  mapper: {
    serializedName: "type",
    type: {
      name: "String"
    }
  }
};
export const type1: msRest.OperationQueryParameter = {
  parameterPath: "type",
  mapper: {
    required: true,
    serializedName: "type",
    type: {
      name: "String"
    }
  }
};
export const userId: msRest.OperationURLParameter = {
  parameterPath: "userId",
  mapper: {
    required: true,
    serializedName: "userId",
    type: {
      name: "String"
    }
  }
};
export const version: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "version"
  ],
  mapper: {
    serializedName: "version",
    type: {
      name: "String"
    }
  }
};
export const voucherId: msRest.OperationQueryParameter = {
  parameterPath: "voucherId",
  mapper: {
    required: true,
    serializedName: "voucherId",
    type: {
      name: "String"
    }
  }
};
