/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export var accuracy = {
    parameterPath: [
        "options",
        "accuracy"
    ],
    mapper: {
        serializedName: "accuracy",
        defaultValue: 0,
        type: {
            name: "Number"
        }
    }
};
export var addressId = {
    parameterPath: "addressId",
    mapper: {
        required: true,
        serializedName: "addressId",
        type: {
            name: "String"
        }
    }
};
export var baseSiteId = {
    parameterPath: "baseSiteId",
    mapper: {
        required: true,
        serializedName: "baseSiteId",
        type: {
            name: "String"
        }
    }
};
export var baseStoreUid = {
    parameterPath: "baseStoreUid",
    mapper: {
        required: true,
        serializedName: "baseStoreUid",
        type: {
            name: "String"
        }
    }
};
export var cartId = {
    parameterPath: "cartId",
    mapper: {
        required: true,
        serializedName: "cartId",
        type: {
            name: "String"
        }
    }
};
export var catalog = {
    parameterPath: [
        "options",
        "catalog"
    ],
    mapper: {
        serializedName: "catalog",
        type: {
            name: "String"
        }
    }
};
export var catalogCode = {
    parameterPath: [
        "options",
        "catalogCode"
    ],
    mapper: {
        serializedName: "catalogCode",
        type: {
            name: "String"
        }
    }
};
export var catalogId = {
    parameterPath: "catalogId",
    mapper: {
        required: true,
        serializedName: "catalogId",
        type: {
            name: "String"
        }
    }
};
export var catalogVersionId = {
    parameterPath: "catalogVersionId",
    mapper: {
        required: true,
        serializedName: "catalogVersionId",
        type: {
            name: "String"
        }
    }
};
export var categoryCode = {
    parameterPath: [
        "options",
        "categoryCode"
    ],
    mapper: {
        serializedName: "categoryCode",
        type: {
            name: "String"
        }
    }
};
export var categoryId = {
    parameterPath: "categoryId",
    mapper: {
        required: true,
        serializedName: "categoryId",
        type: {
            name: "String"
        }
    }
};
export var code0 = {
    parameterPath: [
        "options",
        "code"
    ],
    mapper: {
        serializedName: "code",
        type: {
            name: "String"
        }
    }
};
export var code1 = {
    parameterPath: "code",
    mapper: {
        required: true,
        serializedName: "code",
        type: {
            name: "String"
        }
    }
};
export var componentId = {
    parameterPath: "componentId",
    mapper: {
        required: true,
        serializedName: "componentId",
        type: {
            name: "String"
        }
    }
};
export var consentCode = {
    parameterPath: "consentCode",
    mapper: {
        required: true,
        serializedName: "consentCode",
        type: {
            name: "String"
        }
    }
};
export var consentTemplateId = {
    parameterPath: "consentTemplateId",
    mapper: {
        required: true,
        serializedName: "consentTemplateId",
        type: {
            name: "String"
        }
    }
};
export var consentTemplateVersion = {
    parameterPath: "consentTemplateVersion",
    mapper: {
        required: true,
        serializedName: "consentTemplateVersion",
        type: {
            name: "Number"
        }
    }
};
export var countyIsoCode = {
    parameterPath: "countyIsoCode",
    mapper: {
        required: true,
        serializedName: "countyIsoCode",
        type: {
            name: "String"
        }
    }
};
export var currentPage = {
    parameterPath: [
        "options",
        "currentPage"
    ],
    mapper: {
        serializedName: "currentPage",
        defaultValue: 0,
        type: {
            name: "Number"
        }
    }
};
export var deliveryModeId = {
    parameterPath: "deliveryModeId",
    mapper: {
        required: true,
        serializedName: "deliveryModeId",
        type: {
            name: "String"
        }
    }
};
export var description = {
    parameterPath: [
        "options",
        "description"
    ],
    mapper: {
        serializedName: "description",
        type: {
            name: "String"
        }
    }
};
export var email = {
    parameterPath: "email",
    mapper: {
        required: true,
        serializedName: "email",
        type: {
            name: "String"
        }
    }
};
export var entryNumber = {
    parameterPath: "entryNumber",
    mapper: {
        required: true,
        serializedName: "entryNumber",
        type: {
            name: "Number"
        }
    }
};
export var extendedMerchantCallback = {
    parameterPath: [
        "options",
        "extendedMerchantCallback"
    ],
    mapper: {
        serializedName: "extendedMerchantCallback",
        defaultValue: false,
        type: {
            name: "Boolean"
        }
    }
};
export var fields0 = {
    parameterPath: [
        "options",
        "fields"
    ],
    mapper: {
        serializedName: "fields",
        defaultValue: 'DEFAULT',
        type: {
            name: "String"
        }
    }
};
export var fields1 = {
    parameterPath: [
        "options",
        "fields"
    ],
    mapper: {
        serializedName: "fields",
        defaultValue: 'BASIC',
        type: {
            name: "String"
        }
    }
};
export var fields2 = {
    parameterPath: "fields",
    mapper: {
        required: true,
        serializedName: "fields",
        defaultValue: 'DEFAULT',
        type: {
            name: "String"
        }
    }
};
export var groupId = {
    parameterPath: "groupId",
    mapper: {
        required: true,
        serializedName: "groupId",
        type: {
            name: "String"
        }
    }
};
export var latitude = {
    parameterPath: [
        "options",
        "latitude"
    ],
    mapper: {
        serializedName: "latitude",
        type: {
            name: "Number"
        }
    }
};
export var location = {
    parameterPath: [
        "options",
        "location"
    ],
    mapper: {
        serializedName: "location",
        type: {
            name: "String"
        }
    }
};
export var longitude = {
    parameterPath: [
        "options",
        "longitude"
    ],
    mapper: {
        serializedName: "longitude",
        type: {
            name: "Number"
        }
    }
};
export var max = {
    parameterPath: "max",
    mapper: {
        required: true,
        serializedName: "max",
        defaultValue: 10,
        type: {
            name: "Number"
        }
    }
};
export var maxCount = {
    parameterPath: [
        "options",
        "maxCount"
    ],
    mapper: {
        serializedName: "maxCount",
        type: {
            name: "Number"
        }
    }
};
export var name = {
    parameterPath: [
        "options",
        "name"
    ],
    mapper: {
        serializedName: "name",
        type: {
            name: "String"
        }
    }
};
export var newLogin = {
    parameterPath: "newLogin",
    mapper: {
        required: true,
        serializedName: "newLogin",
        type: {
            name: "String"
        }
    }
};
export var newParameter = {
    parameterPath: "newParameter",
    mapper: {
        required: true,
        serializedName: "new",
        type: {
            name: "String"
        }
    }
};
export var old = {
    parameterPath: [
        "options",
        "old"
    ],
    mapper: {
        serializedName: "old",
        type: {
            name: "String"
        }
    }
};
export var oldCartId = {
    parameterPath: [
        "options",
        "oldCartId"
    ],
    mapper: {
        serializedName: "oldCartId",
        type: {
            name: "String"
        }
    }
};
export var pageLabelOrId = {
    parameterPath: [
        "options",
        "pageLabelOrId"
    ],
    mapper: {
        serializedName: "pageLabelOrId",
        type: {
            name: "String"
        }
    }
};
export var pageSize0 = {
    parameterPath: [
        "options",
        "pageSize"
    ],
    mapper: {
        serializedName: "pageSize",
        defaultValue: 10,
        type: {
            name: "Number"
        }
    }
};
export var pageSize1 = {
    parameterPath: [
        "options",
        "pageSize"
    ],
    mapper: {
        serializedName: "pageSize",
        defaultValue: 20,
        type: {
            name: "Number"
        }
    }
};
export var pageSize2 = {
    parameterPath: [
        "options",
        "pageSize"
    ],
    mapper: {
        serializedName: "pageSize",
        defaultValue: 2147483647,
        type: {
            name: "Number"
        }
    }
};
export var pageType = {
    parameterPath: [
        "options",
        "pageType"
    ],
    mapper: {
        serializedName: "pageType",
        defaultValue: 'ContentPage',
        type: {
            name: "String"
        }
    }
};
export var password = {
    parameterPath: "password",
    mapper: {
        required: true,
        serializedName: "password",
        type: {
            name: "String"
        }
    }
};
export var paymentDetailsId = {
    parameterPath: "paymentDetailsId",
    mapper: {
        required: true,
        serializedName: "paymentDetailsId",
        type: {
            name: "String"
        }
    }
};
export var productCode0 = {
    parameterPath: [
        "options",
        "productCode"
    ],
    mapper: {
        serializedName: "productCode",
        type: {
            name: "String"
        }
    }
};
export var productCode1 = {
    parameterPath: "productCode",
    mapper: {
        required: true,
        serializedName: "productCode",
        type: {
            name: "String"
        }
    }
};
export var promotionGroup = {
    parameterPath: [
        "options",
        "promotionGroup"
    ],
    mapper: {
        serializedName: "promotionGroup",
        type: {
            name: "String"
        }
    }
};
export var promotionId = {
    parameterPath: "promotionId",
    mapper: {
        required: true,
        serializedName: "promotionId",
        type: {
            name: "String"
        }
    }
};
export var query = {
    parameterPath: [
        "options",
        "query"
    ],
    mapper: {
        serializedName: "query",
        type: {
            name: "String"
        }
    }
};
export var radius = {
    parameterPath: [
        "options",
        "radius"
    ],
    mapper: {
        serializedName: "radius",
        defaultValue: 100000,
        type: {
            name: "Number"
        }
    }
};
export var referenceType = {
    parameterPath: "referenceType",
    mapper: {
        required: true,
        serializedName: "referenceType",
        type: {
            name: "String"
        }
    }
};
export var responseUrl = {
    parameterPath: "responseUrl",
    mapper: {
        required: true,
        serializedName: "responseUrl",
        type: {
            name: "String"
        }
    }
};
export var saveCartDescription = {
    parameterPath: [
        "options",
        "saveCartDescription"
    ],
    mapper: {
        serializedName: "saveCartDescription",
        type: {
            name: "String"
        }
    }
};
export var saveCartName = {
    parameterPath: [
        "options",
        "saveCartName"
    ],
    mapper: {
        serializedName: "saveCartName",
        type: {
            name: "String"
        }
    }
};
export var saved = {
    parameterPath: "saved",
    mapper: {
        required: true,
        serializedName: "saved",
        defaultValue: false,
        type: {
            name: "Boolean"
        }
    }
};
export var savedCartsOnly = {
    parameterPath: [
        "options",
        "savedCartsOnly"
    ],
    mapper: {
        serializedName: "savedCartsOnly",
        defaultValue: false,
        type: {
            name: "Boolean"
        }
    }
};
export var searchQueryContext = {
    parameterPath: [
        "options",
        "searchQueryContext"
    ],
    mapper: {
        serializedName: "searchQueryContext",
        type: {
            name: "String"
        }
    }
};
export var securityCode = {
    parameterPath: [
        "options",
        "securityCode"
    ],
    mapper: {
        serializedName: "securityCode",
        type: {
            name: "String"
        }
    }
};
export var sort0 = {
    parameterPath: [
        "options",
        "sort"
    ],
    mapper: {
        serializedName: "sort",
        type: {
            name: "String"
        }
    }
};
export var sort1 = {
    parameterPath: [
        "options",
        "sort"
    ],
    mapper: {
        serializedName: "sort",
        defaultValue: 'asc',
        type: {
            name: "String"
        }
    }
};
export var statuses = {
    parameterPath: [
        "options",
        "statuses"
    ],
    mapper: {
        serializedName: "statuses",
        type: {
            name: "String"
        }
    }
};
export var storeId = {
    parameterPath: "storeId",
    mapper: {
        required: true,
        serializedName: "storeId",
        type: {
            name: "String"
        }
    }
};
export var storeName = {
    parameterPath: "storeName",
    mapper: {
        required: true,
        serializedName: "storeName",
        type: {
            name: "String"
        }
    }
};
export var term = {
    parameterPath: "term",
    mapper: {
        required: true,
        serializedName: "term",
        type: {
            name: "String"
        }
    }
};
export var timestamp0 = {
    parameterPath: [
        "options",
        "timestamp"
    ],
    mapper: {
        serializedName: "timestamp",
        type: {
            name: "String"
        }
    }
};
export var timestamp1 = {
    parameterPath: "timestamp",
    mapper: {
        required: true,
        serializedName: "timestamp",
        type: {
            name: "String"
        }
    }
};
export var toMergeCartGuid = {
    parameterPath: [
        "options",
        "toMergeCartGuid"
    ],
    mapper: {
        serializedName: "toMergeCartGuid",
        type: {
            name: "String"
        }
    }
};
export var type0 = {
    parameterPath: [
        "options",
        "type"
    ],
    mapper: {
        serializedName: "type",
        type: {
            name: "String"
        }
    }
};
export var type1 = {
    parameterPath: "type",
    mapper: {
        required: true,
        serializedName: "type",
        type: {
            name: "String"
        }
    }
};
export var userId = {
    parameterPath: "userId",
    mapper: {
        required: true,
        serializedName: "userId",
        type: {
            name: "String"
        }
    }
};
export var version = {
    parameterPath: [
        "options",
        "version"
    ],
    mapper: {
        serializedName: "version",
        type: {
            name: "String"
        }
    }
};
export var voucherId = {
    parameterPath: "voucherId",
    mapper: {
        required: true,
        serializedName: "voucherId",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map