/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";

const packageName = "occ-client";
const packageVersion = "0.2.0";

export class CommerceWebservicesV2Context extends msRest.ServiceClient {

  /**
   * Initializes a new instance of the CommerceWebservicesV2Context class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.CommerceWebservicesV2Options) {

    if (!options) {
      options = {};
    }
    if(!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(undefined, options);

    this.baseUri = options.baseUri || this.baseUri || "http://localhost:9002";
    this.requestContentType = "application/json; charset=utf-8";

  }
}
